# Generated by Django 5.1 on 2025-01-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_offer_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='validate_offerdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
