# Generated by Django 5.1.5 on 2025-02-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_offer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='applicable_category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='applicable_product',
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_category',
            field=models.ManyToManyField(blank=True, related_name='category_offers', to='product.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_product',
            field=models.ManyToManyField(blank=True, related_name='product_offers', to='product.product'),
        ),
    ]
