# Generated by Django 5.1.5 on 2025-02-07 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
