# Generated by Django 5.1.5 on 2025-02-07 07:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_coupon_expiration_date_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_amount',
            new_name='max_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='Default Coupon', max_length=255),
            preserve_default=False,
        ),
    ]
