# Generated by Django 5.1.5 on 2025-02-12 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 12, 7, 34, 24, 101762, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
