# Generated by Django 5.1 on 2025-01-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_address_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
